# Calra Sim Config Parameters
carla:
  server: '127.0.0.1'
  port: 2000
  autopilot: False
  timeout: 200
  world: 'Town10HD_Opt'
  vehicle_tag: 'charger_2020'

sim:
  default_control: 'xboxone'
  windows:
    front_res: [1920,1080]
    mirror_res: [640,480]
  controls:
    G29_Racing_Wheel:
        steering_wheel: 0
        throttle: 2
        brake: 3
        reverse: 5
        handbrake: 4
    xboxone:
      steering_wheel: 0
      throttle: 5
      brake: 4
      reverse: 5
      handbrake: 4 